### ISSUE TITLE
3 sum problemm leetcode

### ISSUE THREAD

**Issue by hound77** [mandliya/algorithms_and_ds_playground#114]

**Comment by YashaswiMailaru** [comment]
Can I work on this issue.

**Comment by hound77** [comment]
sure but it must be valid work

**Comment by YashaswiMailaru** [comment]
@hound77 can you please describe the problem.

**Comment by YashaswiMailaru** [comment]
@hound77 Done with the work please check it out.

**Comment by hound77** [comment]
invalid solution format as well as i have submitted same code earlier
