### ISSUE TITLE
memory leak in removeDuplicatesFromSortedList.cpp

### ISSUE THREAD

**Issue by ManikanthaP** [mandliya/algorithms_and_ds_playground#94]
after finding a duplicate element the node isn't deleted which causes memory leak.

**Comment by BalajiG2000** [comment]
Memory Leak can be prevented only by deleting the node before reassigning links. You can use a temporary pointer to point the duplicate location and use it to free space .
I hope this code helps you.
[https://www.geeksforgeeks.org/remove-duplicates-from-a-sorted-linked-list/](https://www.geeksforgeeks.org/remove-duplicates-from-a-sorted-linked-list/)
Also close this issue when you are clear.
